apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ebpf-guard
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: ebpf-guard
  template:
    metadata:
      labels:
        app: ebpf-guard
    spec:
      hostPID: true
      hostNetwork: true
      serviceAccountName: default
      containers:
        - name: ebpf-guard
          image: ghcr.io/wythwool/ebpf-guard:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          ports:
            - containerPort: 9108
              name: metrics
          args:
            - -prom
            - -json
            - -rules
            - /etc/ebpf-guard/rules.yaml
          volumeMounts:
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: proc
              mountPath: /proc
              readOnly: true
            - name: modules
              mountPath: /lib/modules
              readOnly: true
            - name: config
              mountPath: /etc/ebpf-guard
      volumes:
        - name: sys
          hostPath:
            path: /sys
        - name: proc
          hostPath:
            path: /proc
        - name: modules
          hostPath:
            path: /lib/modules
        - name: config
          hostPath:
            path: /etc/ebpf-guard
            type: DirectoryOrCreate
